name: keiba_ai_yosou
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.1+4

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.9
  html: 0.15.5+1
  logging: ^1.3.0
  cached_network_image: ^3.4.1
  flutter_html: ^3.0.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  google_fonts: ^8.2.1
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_header.png
    - assets/images/ranking_header.png
    - assets/images/ranking_header2.png
    - assets/images/review_header.png
    - assets/images/blog_header.png            
    - assets/images/prediction_header.png
    - assets/images/medal_gold.png
    - assets/images/medal_silver.png
    - assets/images/medal_bronze.png
    - assets/images/medal_4th.png
    - assets/images/medal_5th.png
    - assets/images/medal_6th.png
    - assets/images/medal_7th.png
    - assets/images/medal_8th.png
    - assets/images/medal_9th.png
    - assets/images/medal_10th.png
    - assets/icon/app_icon.png
    - assets/icon/home.png
    - assets/icon/ranking.png
    - assets/icon/review.png
    - assets/icon/blog.png
    - assets/icon/AI prediction.png

flutter_launcher_icons:

  android: true

  ios: true

  image_path: "assets/icon/app_icon.png"

  adaptive_icon_background:
      "#1A237E"

  adaptive_icon_foreground:
      "assets/icon/app_icon.png"